### ISSUE TITLE
[Bug Report]: Blueprint bug or missing feature?

### ISSUE THREAD

**Issue by LettereUniche** [Deaadman/mod-component-sdk#2]
### Bug Description

Frankly no idea if it's a bug or something that isn't implemented yet, but when making blueprints or recipes and using any powder/liquids you can't set it the value of kg/L to decimals.

### SDK Version

Version 1.0.4

### Steps to Reproduce

1. Create a new prefab
2. Add a new script "Mod.Components.Blueprints" and choose Mod Blueprint
3. Add a new element to required liquid or powder
4. Choose one liquid/powder item and when trying to set the volume/quantity set it to 1,5 (it seems like you can't put dots in there) 
5. Press enter and the comma disappears (after exporting, ingame shows the blueprint requires only 1 kg/L)

### Expected Behaviour

For example in one of my blueprints i can't set the water requirement to 1.5 L (i can set it to 1 or 2 L in order to be more or less close to that range).
Same goes for anything else using kg.

As i said before, i have no idea whether this is a bug or something that isn't implemented yet.
Unless there's some other way i don't know of adding decimals to the value.

**Comment by Deaadman** [comment]
Thank you for picking up on this, it is definitely a bug. I've set the `VolumeInLitres` field to an `integer` whereas the value is actually a `float`.

The reason you can't add a decimal point after any digit is because integer's don't allow that, thank you for reporting this issue - it'll be fixed whenever the next update comes out!

**Comment by Deaadman** [comment]
This issue should now be fixed in [v1.0.5](https://github.com/Deaadman/ModComponentSDK/releases/tag/v1.0.5).

Thank you for the bug report!
